FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install -g dotnet-ef --version 3.1.12
COPY . /app
WORKDIR /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
RUN chmod +x ./migrationAndSeed.bash
CMD /bin/bash ./migrationAndSeed.bash
