version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
    identityseed:
        build: 
            dockerfile: Dockerfile-Migration
            context: ./IdentityServerAspNetIdentity
        environment:
            - ConnectionStrings__DefaultConnection=server=db;database=Identity;User Id=sa;password=Your_password123;trusted_connection=false;
        depends_on:
            - db
    externalidentityseed:
        build: 
            dockerfile: Dockerfile-Migration
            context: ./ExternalIdentityServerAspNetIdentity
        environment:
            - ConnectionStrings__DefaultConnection=server=db;database=ExternalIdentity;User Id=sa;password=Your_password123;trusted_connection=false;
        depends_on:
            - db